### ISSUE TITLE
missing files linked from data

### ISSUE THREAD

**Issue by xrotwang** [clld/amsd-data#10]
The following list of file names is referenced from the CSV data, but wasn't in the set of files provided by @Bibiko : 
```
x_1912-Danzel-Die_Anfaenge_der_Schrift.pdf -- 7x
2018-Kenny-lexeme-tjarita.png -- 2x
PMH-2004.24.33790.png -- 2x
1878-Brough_Smythe-Aborigines_of_Victoria-vol1-reduced.pdf -- 1x
1904-Klaatsch-MalakMalak-Erkenbrecht2010p37.png -- 1x
2010-Erkenbrecht-Klaatsch-Abb30BotenstabHolz.png -- 1x
2018-GuanLim-message-sticks-1a.jpg -- 1x
2018-GuanLim-message-sticks-1b.jpg -- 1x
2018-GuanLim-message-sticks-2a.png -- 1x
2018-GuanLim-message-sticks-2b.png -- 1x
2018-GuanLim-message-sticks-3a.png -- 1x
2018-GuanLim-message-sticks-3b.png -- 1x
2018-GuanLim-message-sticks-4a.jpg -- 1x
2018-GuanLim-message-sticks-4b.jpg -- 1x
2018-GuanLim-message-sticks-5a.jpg -- 1x
2018-GuanLim-message-sticks-5b.jpg -- 1x
2018-GuanLim-message-sticks-6a.jpg -- 1x
2018-GuanLim-message-sticks-6b.jpg -- 1x
2018-GuanLim-message-sticks-7a.jpg -- 1x
2018-GuanLim-message-sticks-7b.jpg -- 1x
20181026-AlwynDoolan.jpg -- 1x
20181026-AlywnDoolan2.jpg -- 1x
20181212-ebay-s-l1600_0.jpg -- 1x
20181212-ebay-s-l1600_1.jpg -- 1x
20181212-ebay-s-l1600_2.jpg -- 1x
20181212-ebay-s-l1600_3.jpg -- 1x
20190131-AlwynDoolan.jpg -- 1x
AMus-E010387_03.jpg -- 1x
AMus-E010387_04.jpg -- 1x
AMus-E010387_05.jpg -- 1x
AMus-E010387_06.jpg -- 1x
AMus-E010387_07.jpg -- 1x
AMus-E010388_01.jpg -- 1x
AMus-E010388_02.jpg -- 1x
AMus-E010388_03.jpg -- 1x
AMus-E010388_04.jpg -- 1x
AMus-E010388_05.jpg -- 1x
AMus-E010388_06.jpg -- 1x
AMus-E010388_07.jpg -- 1x
AMus-E010388_08.jpg -- 1x
AMus-E013385_01.jpg -- 1x
AMus-E013385_02.jpg -- 1x
AMus-E013385_03.jpg -- 1x
AMus-E013400_01.jpg -- 1x
AMus-E013400_02.jpg -- 1x
AMus-E013400_03.jpg -- 1x
AMus-E013400_04.jpg -- 1x
AMus-E013401_02.jpg -- 1x
AMus-E013401_03.jpg -- 1x
AMus-E013402_01.jpg -- 1x
AMus-E013402_02.jpg -- 1x
AMus-E013402_03.jpg -- 1x
AMus-E013404_01.jpg -- 1x
AMus-E013404_02.jpg -- 1x
AMus-E013404_03.jpg -- 1x
AMus-E013405_01.jpg -- 1x
AMus-E013405_02.jpg -- 1x
AMus-E013405_03.jpg -- 1x
AMus-E013406_01.jpg -- 1x
AMus-E013406_02.jpg -- 1x
AMus-E013407_01.jpg -- 1x
AMus-E013407_02.jpg -- 1x
AMus-E013407_03.jpg -- 1x
AMus-E013408_01.jpg -- 1x
AMus-E013408_02.jpg -- 1x
AMus-E013408_03.jpg -- 1x
AMus-E013409_01.png -- 1x
AMus-E013409_02.png -- 1x
AMus-E013409_03.png -- 1x
AMus-E013410.jpg -- 1x
AMus-E013411_01.jpg -- 1x
AMus-E013411_02.jpg -- 1x
AMus-E013411_03.jpg -- 1x
AMus-E013412_02.jpg -- 1x
AMus-E013412_03.jpg -- 1x
AMus-E013412_04.jpg -- 1x
AMus-E013412_05.jpg -- 1x
AMus-E013412_06.jpg -- 1x
AMus-E013412_07.jpg -- 1x
AMus-E013412_08.jpg -- 1x
AMus-E013412_09.jpg -- 1x
AMus-E013412_10.jpg -- 1x
AMus-E013412_11.jpg -- 1x
AMus-E013412_12.jpg -- 1x
AMus-E013412_13.jpg -- 1x
AMus-E013412_14.jpg -- 1x
AMus-E013412_15.jpg -- 1x
EMB-VI_4646-01.png -- 1x
EMB-z-Katalog-VI_4696_4697-c-ANNOTATED-PK.png -- 1x
GML-Au632-07.png -- 1x
NMA198500590398_Milne_exp1.png -- 1x
NMA198500590398_Milne_exp2.png -- 1x
PMH-2004.24.17266.png -- 1x
PMH-z-Catalogue-326870_D4047_page.png -- 1x
PMH-z-Catalogue-326870_D4054_page.png -- 1x
w_1912-Artefact_fig01-Danzel-Die_Anfaenge_der_Schrift-p228.JPG -- 1x
x_1882-Virchow-australischer_botenstoecke.pdf -- 1x
y-EMB-VI_4646-01.png -- 1x
```

**Comment by Bibiko** [comment]
@perezkelly It seems I had an old image archive on my local machine - could you please upload the latest one.

**Comment by perezkelly** [comment]
Hi everyone,
I can do that but I've just noticed a Nextcloud issue: every single one of
our folders on The Message Stick Project is empty!

I could piece it all together again from backups but right now I need to
sort this out with the helpdesk in hopes there is a quicker and more
accurate solution. I will get back to you as soon as it is all restored.

Piers

**Comment by xrotwang** [comment]
Hm. I downloaded the data from https://oc.gnz.mpg.de/owncloud/index.php/s/zjawbK5QYqAMR1z and it still seems to be there.

**Comment by perezkelly** [comment]
The direct link still works for me, but the actual folder in which it sits
is shown as empty.
I've a feeling this has happened before and I can't remember the solution.
When it's sorted out I think I will move everything over to Dropbox.

**Comment by perezkelly** [comment]
Hi all, couldn't find the solution so I'm restoring everything from
backups. When everything is complete again I will notify you and provide an
updated image folder.

**Comment by perezkelly** [comment]
Here is the new image folder to replace the old one. All the files listed
in the .CSV file should be in here:
https://www.dropbox.com/sh/6o8tnklxt9350ye/AAAh-wSV3Tzns3cSZXmJLM3La?dl=0

Please let me know if anything's missing!

**Comment by Bibiko** [comment]
@perezkelly Ok - I've found the missing files except for these both:
00-Text_reference.png
00-No_image_available.png

The latter one seems to be a placeholder which I can generate - But the first one?

**Comment by perezkelly** [comment]
They're actually both placeholders, which is why I forgot to put them in the folder. Here they are attached: 
![00-No_image_available](https://user-images.githubusercontent.com/9706926/58095406-3e985f80-7bd3-11e9-8a82-da568ae69d1c.png)
![00-Text_reference](https://user-images.githubusercontent.com/9706926/58095407-3e985f80-7bd3-11e9-9807-f2b28e6851ae.png)

**Comment by Bibiko** [comment]
thanks - then it turned out the images GML-Au632-03.png and GML-Au632-07.png are identical - how should we solve it? - I'd delete one of them and replace the them by the other one in records.tsv

**Comment by perezkelly** [comment]
Hi, you can delete GML-Au632-07.png
Thanks!
