### ISSUE TITLE
Invalid ID?

### ISSUE THREAD

**Issue by xrotwang** [clld/amsd-data#8]
Is the leading `4` in AMSD ID `4PRM1989.46.9` a typo?

**Comment by Bibiko** [comment]
it seems so - but these amsd_ids won't be used as id within the database

**Comment by perezkelly** [comment]
It's a typo.
The AMSD ids are only for some but not all of the artefacts. I developed
them as a way of quickly citing individual entries in academic papers, so
that I didn't have to use a DOI.

**Comment by xrotwang** [comment]
@Bibiko considering what @perezkelly says, it seems they should be used as ID in the database, no?

**Comment by Bibiko** [comment]
they will be stored in the database as normal info field but they won't be used as internal primary keys since there are only a few of such amsd_ids yet

**Comment by xrotwang** [comment]
Primary keys are always integers an not exposed from the web app in clld apps. The `id` column on the other hand is a unique string which can be used as URL component, and is exposed as the primary, linkable identifier of a record. Since all resources require such an ID, we'd have to make one up anyway. Why not use `amsd_id` in the cases it is defined?

**Comment by Bibiko** [comment]
ok - of course - then the dots within these amid_ids should be replaced by underscores as in PMH305470_D3450.1 PMH305470_D3450.2 etc. @perezkelly 948 amsd_ids are missing, and ILI1948P102F3 occurs twice (not unique ids). How difficult would it be to add those?

**Comment by perezkelly** [comment]
Hmm, since I don't have access to research assistants at the moment it
would take me a long time to generate IDs. Is there some way an ID could be
automatically generated? At least for now? I will fix the dual entry of
ILI1948P102F3
